from setuptools import setup


setup(
    name='smsaero_api',
    version='2.2.0',
    description='Send SMS via smsaero.ru gate',
    keywords=['sms', 'sendings', 'hlr', 'viber', 'calls', 'whatsapp'],
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    author='SmsAero',
    author_email='admin@smsaero.ru',
    url='https://smsaero.ru/integration/class/python',
    license='MIT',
    packages=['smsaero'],
    include_package_data=True,
    install_requires=[
        'setuptools',
        'requests',
    ],
    zip_safe=False,
    classifiers=[
        'Development Status :: 5 - Production/Stable',
        'Environment :: Web Environment',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: GNU General Public License (GPL)',
        'Operating System :: OS Independent',
        'Programming Language :: Python',
        'Programming Language :: Python :: 2',
        'Programming Language :: Python :: 2.7',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
        'Topic :: Internet :: WWW/HTTP',
        'Topic :: Software Development :: Libraries :: Python Modules',
    ],
)
